# This is a demo docker-compose file.
# Usage: docker-compose -f docker-compose-demo.yml up [-d]

version: '3.4'

services:
  reaction:
    image: reactioncommerce/reaction:latest
    depends_on:
      - mongo
    ports:
      - "80:3000"
    environment:
      ROOT_URL: "squash.io"
      MONGO_URL: "mongodb://mongo:27017/reaction"

  mongo:
    image: mongo:3.6.3
    command: mongod --storageEngine=wiredTiger
